### ISSUE TITLE
Winter palette

### ISSUE THREAD

**Issue by aftonsteps** [aftonsteps/colordew#3]
It would be nice to have a winter-themed palette. Ideally this palette would showcase the colors of winter scenery.

**Comment by jacquietran** [comment]
Here's a suggestion for a Stardew-y winter palette! I haven't checked it yet using the `colorblindr` package but will do that now...

```r
winter <- c("#29385b", "#296b97", "#2c9ca7", "#81c9fc", "#b6dcf3", "#c8f5ff",
            "#eabca7", "#ae7d76")
plot(prismatic::color(winter))
```

![winter_suggestion](https://user-images.githubusercontent.com/10459045/140599041-c51419a2-aa59-4640-bf48-0f0c99e6c6dc.png)
